/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, ContractRunner } from "ethers";
import type { AddressFilter, AddressFilterInterface } from "../AddressFilter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "accounts_",
        type: "address[]",
      },
    ],
    name: "viewAddressInfo",
    outputs: [
      {
        internalType: "uint256[]",
        name: "info",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AddressFilter__factory {
  static readonly abi = _abi;
  static createInterface(): AddressFilterInterface {
    return new Interface(_abi) as AddressFilterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AddressFilter {
    return new Contract(address, _abi, runner) as unknown as AddressFilter;
  }
}
